### Generate an image with sdxl
POST {{baseProxyUrl}}:{{proxyPort}}/txt2img
Content-Type: application/json

{
  "model": "sdxl-turbo",
  "prompt": "A photo of a cat in a hat, digital art"
}

### Generate an image with sd
POST {{baseProxyUrl}}:{{proxyPort}}/txt2img
Content-Type: application/json

{
  "model": "sd-turbo",
  "prompt": "A photo of a cat in a hat, digital art"
}

### Chat request, no stream
POST {{baseProxyUrl}}:{{proxyPort}}/api/chat
Content-Type: application/json

{
  "model": "codestral",
  "prompt": "Why is the sky blue?",
  "stream": false
}

### Generate request, no stream
POST {{baseProxyUrl}}:{{proxyPort}}/api/generate
Content-Type: application/json

{
  "model": "codestral",
  "prompt": "Why is the sky blue?",
  "stream": false
}

### Chat request, streaming
POST {{baseProxyUrl}}:{{proxyPort}}/api/chat
Content-Type: application/json

{
  "model": "codestral",
  "prompt": "Why is the sky blue?"
}

### Generate request, streaming
POST {{baseProxyUrl}}:{{proxyPort}}/api/generate
Content-Type: application/json

{
  "model": "codestral",
  "prompt": "Why is the sky blue?"
}

### Clear the Redis cache
DELETE {{baseProxyUrl}}:{{proxyPort}}/cache
